my_login_app/urls.py
from django.urls import path
from . import views

app_name='my_login_app'

urlpatterns=[
    
    path('',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout'),
    path('profile/',views.profile_view,name='profile'),
    path('home/',views.home, name = 'home'),
    path('message_response',views.message_response,name='message_response')
     
    ]

my_login_project/urls.py
from django.contrib import admin
from django.urls import path,include
from my_login_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',views.home,name='home'),
    path('registration/',views.registration_view,name='registration'),
    path('',include('my_login_app.urls')),
    path('message_response',views.message_response,name='message_response'),
    
]

my_login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
# Create your models here.
class UserProfile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    email=models.EmailField(blank=True)
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    portfolio=models.URLField(blank=True)

    def __str__(self):
        return self.user.username
    


class ChatHistory(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    message = models.TextField()
    response = models.TextField()
    def __str__(self):
        # Customize this to display the information you find most useful
        return f"Chat on {self.timestamp} by {self.user.username}"

my_login_app/views.py
from django.shortcuts import render,HttpResponse
from django.contrib.auth.models import User
from my_login_app.models import UserProfile
import sys
from openai import OpenAI
import os


#  fetching from config method.
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
client = OpenAI(api_key=OPENAI_API_KEY)




from pathlib import Path
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth import login,logout
from .models import ChatHistory

my_directory=Path(__file__).resolve().parent.parent
sys.path.append(my_directory)


from custom_auth_backend import MyEmailBackend
# Create your views here.
def home(request):
            if request.user.is_authenticated:
                history = ChatHistory.objects.filter(user=request.user).order_by('-timestamp')
                for record in history:
                    record.response = record.response.replace('<br>', '\n')
                return render(request,'my_login_app/home.html',{'history': history})
            else:   
                return render(request,'my_login_app/login.html')
            

def registration_view(request):
    is_registered=False

    if request.method =="POST":
       
        full_name=request.POST.get('full_name')
        password=request.POST.get('password')
        email=request.POST.get('email')


        user=User()
        user.username=full_name
        user.set_password(password)
        user.email=email
        user.save()

        userProfile=UserProfile()
        userProfile.user=user
        userProfile.save()
        is_registered=True





    return render(request,'my_login_app/registration.html',{'is_registered':is_registered})


def logout_view(request):

    logout(request)
    return HttpResponseRedirect(reverse('my_login_app:login'))



def login_view(request):

    if request.user.is_authenticated:
        history = ChatHistory.objects.filter(user=request.user).order_by('-timestamp')
        for record in history:
            record.response = record.response.replace('<br>', '\n')

        return render(request,'my_login_app/home.html',{'history': history})

    else:
        if(request.method =="POST"):

            email=request.POST.get('email')
            password=request.POST.get('password')

            user=MyEmailBackend.authenticate(request=request,username=email,password=password)

            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('home'))
                else:
                    return HttpResponse("User is not Active.")

            else:
                return HttpResponse("Wrong login details provided.")



        else:
            return render(request,'my_login_app/login.html')


def profile_view(request):
    userProfile=UserProfile.objects.get(user=request.user)
    
    if request.method=="POST":
        if userProfile:
            profile_name=request.POST.get('name')
            profile_portfolio=request.POST.get('portfolio')
    
            profile_pic=request.FILES['profile_pic']

            
            if request.user.username!=profile_name:
                request.user.username=profile_name

            if userProfile.portfolio!=profile_portfolio:
                userProfile.portfolio=profile_portfolio

            if userProfile.profile_pic!=profile_pic:
                userProfile.profile_pic=profile_pic

            request.user.save()
            userProfile.save()


        
    if userProfile:
        name=userProfile.user.username
        email=userProfile.user.email
        portfolio=userProfile.portfolio

        return render(request,'my_login_app/profile.html',context={'profile_name':name,'profile_email':email,'portfolio':portfolio})
   
    

import json  # Ensure json is imported


def message_response(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            received_message = request.POST.get('chat-input1', '')
            received_role = request.POST.get('role')

            original_message = f"{received_role} And {received_message}"

            # Assuming the OpenAI client is correctly configured beforehand
            response = client.chat.completions.create(
                model="gpt-3.5-turbo",
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": "You are a helpful assistant designed to output JSON."},
                    {"role": "user", "content": original_message}
                ]
            )

            response_string = response.choices[0].message.content
            # Parse the JSON string into a Python dictionary
            response_data = json.loads(response_string)

            # Extract and format only the values from the response_data
            values_only = [str(value).replace('\n', '<br>') for value in response_data.values()]

            # Convert list of values into a single string with HTML line breaks for separation
            bot_response = "<br>".join(values_only)

            # Your logic for managing chat history
            # Save the message and bot_response, manage the chat history as before

            ChatHistory.objects.create(user=request.user, message=original_message, response=bot_response)

            # Retrieve the latest 15 records again after creating the new entry
            history = ChatHistory.objects.filter(user=request.user).order_by('-timestamp')[:15]

            # When displaying, you now have a bot_response that is only values
            # No need for additional processing before rendering in the template

            return render(request, 'my_login_app/response.html', {
                'response': bot_response,  # This is now a string of values only
                'message': original_message,
                'history': history
            })

    else:
        return render(request, 'my_login_app/login.html')

templates/my_login_app/base.html
<!DOCTYPE html> {% load static %} <html>
  <head>
    <link href="{% static 'css/basic.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.2.1/dist/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css" />

   <link rel="shortcut icon" href="https://auburnsolutions.com/images/logo.png" type="image/x-icon"> 
    <title>GPT AI Chat</title>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap');

      body,
      html {
        height: 100%;
        margin: 0;
        font-family: "Quicksand", sans-serif;
        background: #eef0f8;
      }

      a,
      p,
      h2,
      h1,
      h3,
      h4,
      h5,
      h6 {
        color: #475f7b !important;
      }

      ul {
        margin: 0;
        padding: 0;
      }

      ul li {
        list-style-type: none;
      }

      a:hover {
        text-decoration: none;
      }

      header {
        background-color: #fff;
      }

      .logo img {
        width: 20%;
        padding: 9px;
      }

      .logo span {
        font-weight: 700;
      }

      li.nav-item.logout a {
        font-size: 16px;
        padding: 0px 0px 3px;
        font-weight: 800;
      }

      .left-panel {
        background: #f7f9fb;
        border-top: 0;
        margin-bottom: 17px;
        margin-top: 18px;
        border-radius: 10px;
        padding: 0px;
        -webkit-transition: .5s;
        transition: .5s;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
        flex-direction: column;
        box-shadow: 0px 0px 5px 0px rgba(71, 95, 123, 0.2);
      }

      .new-chat {
        color: #475f7b;
        display: block;
        padding: 1.5rem 1.5rem;
        position: relative;
        border-bottom: 1px solid rgba(0, 0, 0, 0.07);
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
        background: #fff;
      }

      .new-chat button {
        color: #475f7b;
        background: no-repeat;
        border: navajowhite;
        padding: 0;
        font-weight: bold;
        font-size: 14px;
      }

      .new-chat button:hover,
      .new-chat button:focus {
        background: none;
        border: none;
        color: #475f7b;
        box-shadow: none;
      }

      .new-chat i:hover {
        color: #0056b3;
        cursor: pointer;
      }

      .chats-history {
        padding: 1.5rem 1.5rem;
        -ms-flex: 1 1 auto;
        flex: 1 1 auto;
        border-radius: 10px;
      }

      .history-bar {
        background: #fff;
        padding: 20px;
        border-radius: 23px;
        margin-bottom: 26px;
        box-shadow: 0px 4px 13px 0px rgba(25, 42, 70, 0.13) !important;
      }

      .card i {
        color: #bd85cf;
      }
      .card-body {
    height: 375px;
    overflow-y: scroll;
    overflow-x: hidden;
}
.card-body ul li {
    background: #f7f9fb;
    padding: 10px;
    margin: 4px 0px;
    border-radius: 7px;
    font-size: 11px;
    font-weight: 500;
    height: 48px;
    overflow: hidden;
}
      .btn-link:hover {
        text-decoration: none;
      }

      div#chat-messages {
    height: 300px;
    overflow-y: scroll;
    overflow-x: hidden;
    background: #fff;
    margin-top: 1rem;
    border-radius: 11px;
    padding: 30px;
    font-size: 13px;
    color: #000;
    font-weight: 600;
    line-height: 28px;
}
      .chat-input .form-group {
    background: #f7f9fb;
    border-radius: 13px;
    padding: 13px 14px 6px;
    margin: 19px 0px 0px;
    border: 2px solid #f7f9fb;
    width: 100%;
    font-weight: 500;
    font-size: 15px;
    color: #757575;
    /* box-shadow: 2px 2px 10px 2px #f7f9fb; */
}
      .chat01 {
        width: 94%;
        border-radius: 13px;
        margin-top: 24px;
        padding: 16px;
        border: 2px solid #f7f9fb;
        color: #757575;
        box-shadow: 2px 2px 10px 2px #f7f9fb;
        font-size: 12px;
      }

      .send_btn {
        background-color: #6993ff;
        border-color: #6993ff;
        color: #fff;
        box-shadow: none;
        border: none;
        padding: 9px 13px;
        border-radius: 100%;
        cursor: pointer;
      }

      .sub_btn {
        border-radius: 7px;
        background-color: #6993ff;
        border-color: #6993ff;
        color: #fff;
        box-shadow: none;
        border: none;
        padding: 8px 22px;
        cursor: pointer;
      }

      .send_btn:hover {
        position: relative;
        cursor: pointer;
        display: inline-block;
        overflow: hidden;
        user-select: none;
        -webkit-tap-highlight-color: transparent;
        vertical-align: middle;
        z-index: 1;
        transition: .3s ease-out;
        box-shadow: 2px 2px 2px 2px #6993ff;
        
      }

      .msg-container {
    background: #fff;
    padding-bottom: 20px;
    border-radius: 10px;
    height: 566px;
}

      .chat-input {
        padding: 1rem 4rem 0.4rem;
      }

      .edit-icon {
    float: right;
}
.navbar{padding:0;}

body.dark {
    background-color:#1c2e4c;
    color: #b5b5c3;
}
/* body.dark header{ background-color: #1c2e4c;} */


body.dark .login-form{background-color: #0c1a32 !important;
    color: #ffffff !important;
}
body.dark .login-form label, body.dark .login-form h1{color: #fff!important;}
.dark .new-chat{border-bottom: 1px solid rgba(255, 255, 255, 0.12);background:inherit;}
.dark .new-chat {color:#fff; opacity: 0.5;}
.dark .left-panel {
    background-color: #0c1a32;
    box-shadow: -7.829px 11.607px 21px 0px rgba(25, 42, 70, 0.13);
}
body.dark h1, body.dark .support a {color: #fff;}

.checkbox {
  opacity: 0;
 
}

.checkbox-label {
  background-color: #111;
  width: 50px;
  height: 26px;
  border-radius: 50px;
  position: relative;
  padding: 5px;
  cursor: pointer;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.fa-moon {color: #f1c40f;}

.fa-sun {color: #f39c12;}

.checkbox-label .ball {
  background-color: #fff;
  width: 22px;
  height: 22px;
  position: absolute;
  left: 2px;
  top: 2px;
  border-radius: 50%;
  transition: transform 0.2s linear;
}

.checkbox:checked + .checkbox-label .ball {
  transform: translateX(24px);
}

/*  Support me if you like it */
.support {
	position: absolute;
	right: 20px;
	bottom: 20px;
}

.support a {
  color: #292c35;
  font-size: 32px;
  backface-visibility: hidden;
  display: inline-block;
  transition: transform 0.2s ease;
}

.support a:hover{
  transform: scale(1.1);
}
li.nav-item.logout {
    padding: 1rem 0;
}
#headingOne button{cursor: inherit !important;}
    </style>
  </head>
  <body>
    <header>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-5">
            <div class="logo">
              <a class="navbar-brand">
                <img src="https://auburnsolutions.com/images/logo.png">
                <span>Auburn ChatBox</span>
              </a>
            </div>
          </div>
          <div class="col-sm-7">
            <nav class="navbar navbar-expand-lg navbar-light">
              <!-- <a class="navbar-brand" href="#">Home</a> -->
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ml-auto"> {% if not user.is_authenticated %} <li class="nav-item active">
                    <a class="nav-link" href="{% url 'registration' %}">Registration <span class="sr-only">(current)</span>
                    </a>
                  </li> {% endif %} {% if request.user.is_authenticated %} <li class="nav-item logout">
                    <a class="nav-link " href="{% url 'my_login_app:logout' %}">
                      <i class="fa fa-sign-out"></i> Logout </a>
                  </li> {% else %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_login_app:login' %}">Login</a>
                  </li> {% endif %} </ul>
              </div>
              
<!-- <div>
    <input type="checkbox" class="checkbox" id="checkbox">
    <label for="checkbox" class="checkbox-label">
      <i class="fa fa-moon"></i>
      <i class="fa fa-sun"></i>
      <span class="ball"></span>
    </label>
  </div> -->
            </nav>
          </div>
        </div>
      </div>
    </header>
    <div class="chat-container">
      <!-- <div class="container"> --> {% block body_block %} {% endblock %}
      <!-- </div> -->
    </div>
    <script>
      window.onload = function() {
        var chatContainer = document.querySelector('.chat-container');
        chatContainer.scrollTop = chatContainer.scrollHeight;
      }
    </script>

    <script>
        const checkbox = document.getElementById("checkbox")
checkbox.addEventListener("change", () => {
  document.body.classList.toggle("dark")
  
})
    </script>

  <!-- to disable the submit button untill all things are selected -->
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var submitButton = document.getElementById('submitButton');
    var radioButtons = document.querySelectorAll('input[type="radio"]');
    var textBox = document.querySelector('input[name="chat-input1"]');

    // Function to check if any radio button is selected
    function isRadioButtonSelected() {
      for (var i = 0; i < radioButtons.length; i++) {
        if (radioButtons[i].checked) {
          return true;
        }
      }
      return false;
    }

    // Function to check if text box is filled
    function isTextBoxFilled() {
      return textBox.value.trim() !== '';
    }

    // Function to enable or disable submit button
    function toggleSubmitButton() {
      submitButton.disabled = !(isRadioButtonSelected() && isTextBoxFilled());
    }

    // Add event listeners to radio buttons and text box
    radioButtons.forEach(function (radioButton) {
      radioButton.addEventListener('change', toggleSubmitButton);
    });
    textBox.addEventListener('input', toggleSubmitButton);

    // Event listener for form submission
    document.getElementById('chatForm').addEventListener('submit', function (event) {
      if (!isRadioButtonSelected() || !isTextBoxFilled()) {
        event.preventDefault();
        alert('Please select a role and fill out the text box before submitting.');
      }
    });

    // Initially disable submit button
    toggleSubmitButton();
  });
</script>





    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/my_login_app/home.html
{% extends 'my_login_app/base.html' %} {% block body_block %} <div class="chat-container1">
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3">
          <div class="chat-window">
            <!-- <h2>Auburn Digital Solutions Chatbot</h2> -->
            <div class="left-panel">
              <form action="{% url 'home' %}" method="post"> {%csrf_token%} <div class="new-chat">
                  <button type="submit" class="btn btn-primary">
                    <i class="fa fa-plus-circle"></i> Start New Chat </button>
              </form>
              <div class="edit-icon">
                <i class="fa fa-edit"></i>
              </div>
            </div>
            <div class="chats-history">
              <div class="">
                <div id="accordionExample3" class="accordion shadow">
                  <!-- Accordion item 1 -->
                  <div class="card">
                    <div id="headingOne" class="card-header bg-white shadow-sm border-0">
                      <h2 class="mb-0">
                        <button type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" class="btn btn-link text-dark font-weight-bold text-uppercase collapsible-link">
                          <i class="fa fa-calendar"></i> History </button>
                      </h2>
                      
                    
                    </div>
                    
                    <div id="collapseOne" aria-labelledby="headingOne" data-parent="#accordionExample" class="collapse show">
                      <div class="card-body">
                        <ul>
                          {% for record in history|slice:":15" %}
                          <li>
                            <a href="#" class="history-item" data-message="{{ record.response|linebreaksbr }}" >{{ record.message|linebreaksbr }}</a>
                          </li>
                          {% endfor %}
                        </ul>
                      </div>
                    </div>
                    
                  </div>
                  <!-- End -->
                  <!-- Accordion item 2 -->
                  <!-- <div class="card">
                    <div id="headingTwo" class="card-header bg-white shadow-sm border-0">
                      <h2 class="mb-0">
                        <button type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" class="btn btn-link collapsed text-dark font-weight-bold text-uppercase collapsible-link">
                          <i class="fa fa-calendar"></i> Previous 7 Days </button>
                      </h2>
                    </div>
                    <div id="collapseTwo" aria-labelledby="headingTwo" data-parent="#accordionExample" class="collapse">
                      <div class="card-body">
                        <ul>
                          <li>
                            <a href="#">List Item 1</a>
                          </li>
                          <li>
                            <a href="#">List Item 1</a>
                          </li>
                          <li>
                            <a href="#">List Item 1</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div> -->
                  <!-- End -->
                  <!-- Accordion item 3 -->
                  <!-- <div class="card">
                    <div id="headingThree" class="card-header bg-white shadow-sm border-0">
                      <h2 class="mb-0">
                        <button type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree" class="btn btn-link collapsed text-dark font-weight-bold text-uppercase collapsible-link">
                          <i class="fa fa-calendar"></i> 2023 </button>
                      </h2>
                    </div>
                    <div id="collapseThree" aria-labelledby="headingThree" data-parent="#accordionExample" class="collapse">
                      <div class="card-body p-5">
                        <ul>
                          <li>
                            <a href="#">List Item 1</a>
                          </li>
                          <li>
                            <a href="#">List Item 1</a>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div> -->
                  <!-- End -->
                </div>
              </div>
            </div>
            
          </div>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="msg-container">
          <div id="chat-messages"> {% block content %} {% endblock%} </div>
          <div class="msg-input">
            <div class="row d-flex justify-content-center">
              <div class="col-sm-12">
                <form id="chatForm" action="{% url 'message_response' %}" method="POST"> {%csrf_token%} <div class="chat-input">
                    
                  <div class="row"  >
                    
                      <div class="col-sm-6">
                        <div class="form-group">
                          <input type="radio" id="role1" name="role" value="Person One">
                          <label for="role1"> Person One</label>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="form-group">
                          <input type="radio" id="role2" name="role" value="Person Two">
                          <label for="role2"> Person Two</label>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="form-group">
                          <input type="radio" id="role3" name="role" value=" Person Three">
                          <label for="role3"> Person Three</label>
                        </div>
                      </div>
                      <div class="col-sm-6">
                        <div class="form-group">
                          <input type="radio" id="role4" name="role" value="Person Four">
                          <label for="role4"> Person Four</label>
                        </div>
                      </div>
                    </div>
                    <div class="row">

                      <div class="col-sm-12">
                        <input type="text" name="chat-input1" placeholder="Got questions? I've got bytes of knowledge..." class="chat01">
                        <!-- <input class="btn btn-primary" type="submit" value="submit"> -->
                        <button id="submitButton" type="submit" value="submit" class="send_btn">
                            <i class="fa fa-paper-plane"></i>
                        </button>
                      </div>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  </div>
  <!-- to present chat history -->
  <!-- <div><div class="chat-container">
              {% for record in history %}
                  <div class="chat-message user-message"><div class="message-content">
                          {{ record.message|linebreaksbr }}
                      </div><div class="message-time">{{ record.timestamp }}</div></div><div class="chat-message bot-message"><div class="message-content">
                          {{ record.response|linebreaksbr }}
                      </div><div class="message-time">{{ record.timestamp }}</div></div>
              {% endfor %}
          </div></div> --> 
          
   <!-- to show history messages -->
   <!-- <script>
    document.addEventListener('DOMContentLoaded', function() {
      var historyItems = document.querySelectorAll('.history-item');
      historyItems.forEach(function(item) {
        item.addEventListener('click', function() {
          var message = this.dataset.message;
          document.getElementById('chat-messages').innerText = message;
        });
      });
    });
  </script> -->

  <!-- to show the history reponse  -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var historyItems = document.querySelectorAll('.history-item');
      historyItems.forEach(function(item) {
        item.addEventListener('click', function() {
          var message = this.dataset.message;
          var formattedMessage = message.replace(/<br>/g, '\n'); // Replace <br> with line breaks
          var chatMessages = document.getElementById('chat-messages');
          
          // Increase the size of chat-messages box
          chatMessages.style.height = '550px'; // Adjust the height as needed
          
          
          // Set the formatted message to chat-messages
          chatMessages.innerText = formattedMessage;
        });
      });
    });
  </script>
  
  
<!-- to disable the options -->
<script>
  document.addEventListener("DOMContentLoaded", function() {
    // Get all history items
    var historyItems = document.querySelectorAll('.history-item');

    // Function to disable the form
    function hideForm() {
      document.getElementById('chatForm').style.display = 'none';
    }

    // Add click event listener to each history item
    historyItems.forEach(function(item) {
      item.addEventListener('click', function() {
        // Hide the form when a history item is clicked
        hideForm();
      });
    });
  });
</script>

<!-- to disable the submit button -->



   
          
          {% endblock %}

templates/my_login_app/index.html
{% extends "my_login_app/base.html" %}


{% block body_block %}


{% endblock %}

templates/my_login_app/login.html
{% extends 'my_login_app/base.html' %} {% block body_block %}
<div class="container-fluid">
<div class="row">
    <div class="col-sm-6 no-padding">
        <div class="right-img bg-white">
            <img src="https://img.freepik.com/premium-vector/mobile-chat-bot-flat-style-design-vector-illustration-stock-illustration_357500-626.jpg" width="100%">
        </div>
    </div>
    <div class="col-sm-6">
        <div class="login-form">
     
            <h1>Login</h1>
            <form method="post"> {% csrf_token %} <div class="form-group">
                <label> Email </label>
                <input type="email" name="email" class="form-control" value="" />
              </div>
              <div class="form-group">
                <label> Password </label>
                <input type="password" name="password" class="form-control" value="" />
              </div>
              <div class="text-center">
                <input type="submit" name="" value="Login" class="sub_btn" />
              </div>
            </form>
          </div> 
    </div>
</div>
</div>
  <style>
    .nav-link {
    display: block;
    padding: 1.5rem 1rem;
    font-weight: 600;
}
 .right-img {
    padding: 5rem 0 4rem;
}
    .no-padding{padding:0;}
    .no-margin{margin:0;}
    .login-form {
      width: 50%;
      background: #fff;
      padding: 20px;
      border-radius: 14px;
      margin: 0 auto;
      border: 1px solid #ddd;
      margin-top: 6rem;
    }
  
    .login-form h1 {
      font-size: 18px;
      font-weight: bold;
      text-align: center;
      margin: 17px;
      text-transform: uppercase;
      font-weight: 900;
    }
  
    .login-form label {
      font-size: 13px;
      color: #777575;
    }
  </style> {% endblock %}

templates/my_login_app/profile.html
{% extends 'my_login_app/base.html' %}

{% block body_block %}

<form enctype="multipart/form-data" method="post">

    {% csrf_token %}
    <label>Full Name:</label>
    <input type="text" name="name" value={{profile_name}} />

    <label>Portfolio:</label>
    <input type="url" name="portfolio" value="" />


    <label>Profile Picture:</label>
    <input type="file" name="profile_pic" accept="image/png, image/jpeg" value="" />


    <input type="submit" name="vv"  value="Submit" />

</form>


{% endblock %}

templates/my_login_app/registration.html
{% extends 'my_login_app/base.html' %}


{% block body_block %}

{% if is_registered == False %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label>Full Name:</label>
    <input type="text" name="full_name" value="" />


    <br />
    <label>Email:</label>
    <input type="email" name="email" value="" />

    <br />

    <label>Password:</label>
    <input type="password" name="password" value="" />

    <br />

    <input type="submit" name="" value="Register" />


</form>

{% else %}

<h1>Registration Successful</h1>



{% endif %}

{% endblock %}

templates/my_login_app/response.html
{% extends 'my_login_app/home.html' %} -->

<!-- your_template.html -->
<div>
    {% block content %}
    {{ response|safe }}
    {% endblock%}
</div>